Update licenta-functions

diff --git a/lic2/licenta-functions b/lic2/licenta-functions
--- a/lic2/licenta-functions
+++ b/lic2/licenta-functions
@@ -696,11 +696,23 @@ collect_suri() {
 	done
 }
 
+validateEmail() {
+  email=$WEBUSER
+  # (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
+  if [[ ! "$email" =~ ^[[:alnum:]._%+-]+@[[:alnum:].-]+\.[[:alpha:]]{2,}$ ]]; then
+    fail "Email address is invalid"
+  fi
+
+  if [[ "$email" =~ [A-Z] ]]; then
+    fail "Email addresses cannot contain uppercase letters"
+  fi
+}
+
 # Get an email & password for the web admin user
 collect_webuser_inputs() {
 	whiptail_create_web_user
-
-	while ! so-user valemail "$WEBUSER" >> "$setup_log" 2>&1; do
+	
+	while ! validateEmail "$WEBUSER" >> "$setup_log" 2>&1; do
 		whiptail_invalid_user_warning
 		whiptail_create_web_user "$WEBUSER"
 	done
